"""
Export slim versions of processed data for Streamlit Cloud deployment.

Reads the full processed CSVs (ignored by git, generated by notebooks) and
writes column-pruned versions to data/app/ that are small enough for GitHub.

Run from repo root:
    python scripts/export_app_data.py
"""

from pathlib import Path
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
PROCESSED_DIR = ROOT / "data" / "processed"
APP_DATA_DIR = ROOT / "data" / "app"

APP_DATA_DIR.mkdir(parents=True, exist_ok=True)

# ---------------------------------------------------------------------------
# banking_complaints.csv → app_complaints.csv
# Needed by: NPS Dashboard (gauge, product bar, pie, trend, channel)
# ---------------------------------------------------------------------------

COMPLAINTS_COLS = [
    "complaint_id",
    "nps_score",
    "nps_segment",
    "product",
    "date_received",
    "submitted_via",
    "company_response_to_consumer",
    "timely_response",
]

src = PROCESSED_DIR / "banking_complaints.csv"
df = pd.read_csv(src, low_memory=False, usecols=lambda c: c in COMPLAINTS_COLS)
df = df[[c for c in COMPLAINTS_COLS if c in df.columns]]
out = APP_DATA_DIR / "app_complaints.csv"
df.to_csv(out, index=False)
print(f"app_complaints.csv  {len(df):,} rows × {len(df.columns)} cols  →  {out.stat().st_size / 1e6:.1f} MB")

# ---------------------------------------------------------------------------
# features_nlp.csv → app_features.csv
# Needed by: Topic Explorer + Customer Segments
# Text columns are truncated to keep file size under GitHub's 50 MB limit.
# ---------------------------------------------------------------------------

FEATURES_COLS = [
    "complaint_id",
    "dominant_topic",
    "topic_name",
    "topic_probability",
    "text_clean",
    "consumer_complaint_narrative",
    "severity_label",
    "cluster",
    "cluster_name",
    "nps_score",
    "nps_segment",
    "product",
    "pca_1",
    "pca_2",
]

TEXT_TRUNCATE = 400  # chars — enough for word clouds and representative complaint display

src2 = PROCESSED_DIR / "features_nlp.csv"
df2 = pd.read_csv(src2, low_memory=False, usecols=lambda c: c in FEATURES_COLS)
df2 = df2[[c for c in FEATURES_COLS if c in df2.columns]]

for col in ("text_clean", "consumer_complaint_narrative"):
    if col in df2.columns:
        df2[col] = df2[col].str[:TEXT_TRUNCATE]

out2 = APP_DATA_DIR / "app_features.csv"
df2.to_csv(out2, index=False)
print(f"app_features.csv    {len(df2):,} rows × {len(df2.columns)} cols  →  {out2.stat().st_size / 1e6:.1f} MB")
